-- vim.api.nvim_set_hl(0, "MiniStatuslineModeNormal", { bold = true })
-- vim.api.nvim_set_hl(0, "CmpItemKindMethod", { fg = "Orange" })
-- vim.api.nvim_set_hl(0, "CmpItemKindSnippet", { fg = "Green" })
-- vim.api.nvim_set_hl(0, "CmpItemMenu", { bg = "Gray" })
-- vim.api.nvim_set_hl(0, "CmpNormal", { bg = "Gray" })

-- vim.api.nvim_set_hl(0, "MiniStatuslineModeVisual", { bold = true })
-- vim.api.nvim_set_hl(0, "MiniTablineModifiedVisible", { italic = true })
-- vim.api.nvim_set_hl(0, "MiniTablineModifiedHidden", { italic = true })
-- vim.api.nvim_set_hl(0, "MiniTablineModifiedCurrent", {
--   italic = true,
--   reverse = true,
-- })
-- vim.api.nvim_set_hl(0, "MiniTablineCurrent", {
--   reverse = true,
-- })
